# Generated by Django 3.2 on 2021-10-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('coach', 'Coach'), ('nutritionist', 'Nutritionist')], default='customer', max_length=20),
        ),
    ]
