# Generated by Django 3.2 on 2021-11-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211030_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
    ]
