# Generated by Django 3.2 on 2021-10-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='name',
        ),
        migrations.AddField(
            model_name='routine',
            name='events',
            field=models.ManyToManyField(blank=True, to='training.Event'),
        ),
    ]
