# Generated by Django 3.2 on 2021-10-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20211021_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutineEvent',
        ),
    ]
