# Generated by Django 3.2 on 2021-11-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20211109_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='events',
        ),
    ]
