# Generated by Django 3.2 on 2021-11-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20211109_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcerciseRoutine',
            new_name='ExerciseRoutine',
        ),
    ]
