# Generated by Django 3.2 on 2021-11-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_auto_20211110_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerroutine',
            name='user',
        ),
    ]
