# Generated by Django 3.2 on 2021-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20211111_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroutine',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
