# Generated by Django 3.2 on 2021-11-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_dayroutine_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayroutine',
            name='enable_day',
        ),
    ]
