# Generated by Django 3.2 on 2021-11-12 03:28

import apps.training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_remove_dayroutine_enable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.training.models.exercise_directory_path),
        ),
    ]
