# Generated by Django 3.2 on 2021-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroutine',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerroutine',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
