# Generated by Django 3.2 on 2021-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20211118_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerroutine',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
