# Generated by Django 3.2 on 2021-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_customerroutine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
