# Generated by Django 3.2 on 2021-11-19 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0024_alter_customerroutine_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerroutine',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coachOf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerroutine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerOf', to=settings.AUTH_USER_MODEL),
        ),
    ]
