# Generated by Django 3.2 on 2021-11-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_customerroutineprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerroutineprogress',
            name='current_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.exerciseroutine'),
        ),
    ]
