# Generated by Django 3.2 on 2021-11-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_alter_customerroutineprogress_current_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerroutineprogress',
            name='total_exercise',
        ),
        migrations.AddField(
            model_name='customerroutineprogress',
            name='completed_exercises',
            field=models.ManyToManyField(blank=True, related_name='completed_exercises', to='training.ExerciseRoutine'),
        ),
        migrations.AlterField(
            model_name='customerroutineprogress',
            name='current_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_exercise', to='training.exerciseroutine'),
        ),
    ]
