# Generated by Django 3.2 on 2021-11-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_auto_20211119_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseroutine',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
