# Generated by Django 3.2 on 2021-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_exercise_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseroutine',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
