# Generated by Django 3.2 on 2021-11-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0031_exerciseroutine_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerroutineprogress',
            name='completed_exercises',
        ),
    ]
