# Generated by Django 3.2 on 2021-11-23 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0032_remove_customerroutineprogress_completed_exercises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseroutine',
            options={'ordering': ['exercise__name']},
        ),
        migrations.RemoveField(
            model_name='exerciseroutine',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='category',
            name='is_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExerciseRoutineProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exerciseroutine')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.customerroutineprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
