# Generated by Django 3.2 on 2021-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_remove_exerciseroutineprogress_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerroutineprogress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
