# Generated by Django 3.2 on 2022-01-06 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_rename_weight_exerciseroutineprogress_exercise_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseroutine',
            name='rest',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
