# Generated by Django 3.2 on 2022-01-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_alter_exerciseroutine_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='exercise',
            name='tag',
            field=models.ManyToManyField(blank=True, to='training.Tag'),
        ),
    ]
