# Generated by Django 3.2 on 2022-01-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_auto_20220109_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='tag',
            new_name='tags',
        ),
    ]
