# Generated by Django 3.2 on 2022-01-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0041_rename_tag_exercise_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='status',
        ),
    ]
