# Generated by Django 3.2 on 2022-01-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0043_auto_20220110_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='warnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
